[project]
name = "blockchain-az"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    {name = "Farzad FARID", email = "farzy@farzy.org"},
]
requires-python = ">=3.10, <4.0"
dependencies = [
    "flask >=2.2.2, <3.0.0",
    "datetime >=5.1, <6.0",
]

[tool.uv]
default-groups = []
